### ISSUE TITLE
Save two characters by using unicode ellipsis

### ISSUE THREAD

**Issue by duetosymmetry** [davidsd/snarxiv-bot#1]
Instead of truncating 3 extra characters, you could truncate 1 extra character and use the unicode ellipsis character: `…`

https://github.com/davidsd/snarxiv-bot/blob/6a6c294bf3c452b275f754a293c1484a39e94a2b/src/Twitter/Bot.hs#L62

**Comment by davidsd** [comment]
Good idea! Done.
